name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - uses: actions/checkout@v3

      # 2) Install the .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3) Restore & build solution
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      # 4) Run your unit/integration tests
      - name: Run tests
        working-directory: ELearning.Tests
        run: dotnet test --no-build --verbosity normal

      # 5) Install EF Core CLI so `dotnet ef` can run
      - name: Install EF Core tool
        run: dotnet tool install --global dotnet-ef --version 8.*

      # 6) Run EF Core migrations
      - name: Apply EF Core migrations
        run: dotnet ef database update --project ELearning.Infrastructure/ELearning.Infrastructure.csproj --startup-project ELearning.API/ELearning.API.csproj


      # 7) Smoke‑test the API’s /health endpoint
      - name: Run health check
        working-directory: ELearning.API
        run: |
          dotnet run --no-build --urls http://localhost:5000 &
          for i in {1..10}; do
            if curl -fs http://localhost:5000/health; then
              echo "API is up!"
              break
            fi
            echo "Waiting for API..."
            sleep 2
          done

